### PR TITLE
Updates the README with details of the  HTTP 1.0 chunked response issue

### PR DESCRIPTION
**Pull request by SHession**
## What does this change?

This PR adds some information related to an issue some users may experience locally, and how to resolve it.

### CODE REVIEW

**Review by jennygrahamjones — APPROVED** [review]
Great addition. Thanks!

**Comment by akash1810** [comment]
I'd recommend updating `dev-nginx` to create the correct nginx configuration file (fix at source). It should be a case of adding the `proxy_http_version 1.1;` directive [here](https://github.com/guardian/dev-nginx/blob/b93f720e19fa5dd0b0d1c20c477f526820d5c96e/script/setup-app#L67-L74).

We're doing this for websockets [here](https://github.com/guardian/dev-nginx/blob/b93f720e19fa5dd0b0d1c20c477f526820d5c96e/script/setup-app#L56) already, so I don't think it will cause any backwards compatibility issues.

**Comment by akash1810** [comment]
I've a need for setting `proxy_http_version` in another project and raised https://github.com/guardian/dev-nginx/pull/21 which might be useful here.

**Comment by akash1810** [comment]
The latest version of dev-nginx (v1.1.1) should solve this and would mean this PR can be closed. Run `brew upgrade guardian/devtools/dev-nginx` to get it.

**Comment by jennygrahamjones** [comment]
> The latest version of dev-nginx (v1.1.1) should solve this and would mean this PR can be closed. Run `brew upgrade guardian/devtools/dev-nginx` to get it.

I've just tried running Viewer locally with this update and it's working as expected 👍

**Pull request closed without merging**
