### PR TITLE
Ad Block

### PR DESCRIPTION
**Pull request by clloyd**
Added new checkbox to Block ads by adding a #noads after the url. Required changes to the reload function, is now switches to about:blank for 1ms before switching to the new url. Without this the #change is ignored.

AdBlock state is stored in localstorage, not per url, so once enabled/disabled will stay enabled/disabled.

### CODE REVIEW

**Comment by alastairjardine** [comment]
> AdBlock state is stored in local storage, not per url, so once enabled/disabled will stay enabled/disabled.

Is there a risk that users will just keep it switched on permanently, thus meaning the impact of ads more broadly will be missed? e.g. content classes etc

**Comment by clloyd** [comment]
@alastairjardine So to solve the iframe busting we need to have Adblock enabled after a page refresh, as once the busting happens it destroys the viewer. How about when it's enabled it's only enabled for the rest of that day?

**Comment by jamespamplin** [comment]
:+1: code looks good. Thanks for this.

**Comment by alastairjardine** [comment]
@clloyd Seems like a reasonable compromise

**Comment by piuccio** [comment]
Do we have metrics for this? It might be interesting to know how many people click on `disable ads`

**Comment by clloyd** [comment]
@piuccio Good point! Adding them in!

**Pull request merged**
