### PR TITLE
Add a new social share viewer

### PR DESCRIPTION
**Pull request by mchv**
This has been asked by audience team so that editorial people can preview how their content will be displayed when shared on social networks.

screen shot 2016-06-24 at 02 24 15

Next steps:
- [x] Display how article is going to be displayed on twitter

2 points we probably need to think about:
- automatically purging facebook graph when we update an article
- adding a new field `socialImage`that will be used only for sharing 

Implementation is quite simple, we only display `open-graph` attributes (`title`, `image` and `description`) from frontend.

@na7hangood @chriswilk

### CODE REVIEW

**Comment by mchv** [comment]
screen shot 2016-06-29 at 12 25 28

**Comment by na7hangood** [comment]
Love this - we need an icon for the tab that isn't the FB "f" or the twitter bird. Would like to keep it generic for sharing platforms. @akemitakagi @alastairjardine what do you think?

**Comment by akemitakagi** [comment]
Emoji faces??

On 29 June 2016 at 12:32, Nathan Good notifications@github.com wrote:

> Love this - we need an icon for the tab that isn't the FB "f" or the
> twitter bird. Would like to keep it generic for sharing platforms.
> @akemitakagi https://github.com/akemitakagi @alastairjardine
> https://github.com/alastairjardine what do you think?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/guardian/editorial-viewer/pull/56#issuecomment-229330323,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFsQReHMEppG9lv8FIGtKop7fbPfzNEpks5qQle-gaJpZM4I9Zs-
> .

## 

---

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by mchv** [comment]
@na7hangood @clloyd may we merge without the final logo? one week is sloooowww 🐌   🐌   🐌  
We could change logo after and people will not care but we will have useful feedback

**Comment by clloyd** [comment]
👍

**Comment by alastairjardine** [comment]
QQ: is this a separate app from http://viewer.gutools.co.uk/, or a new thing _within_ viewer?

If so...where is the 'mobile checked and verified' button? Similarly, where's copy taste gone?

If it's a new thing, let's chat :) It might be confusing given the visual treatments are so similar to viewer (the icon is identical). We may need to page @akemitakagi for a new one.

**Comment by na7hangood** [comment]
It is viewer - Mariot did a bad screengrab. Those tabs are there - honest.

On 30 June 2016 at 10:03, Alastair Jardine notifications@github.com wrote:

> QQ: is this a separate app from http://viewer.gutools.co.uk/, or a new
> thing _within_ viewer?
> 
> If so...where is the 'mobile checked and verified' button? Similarly,
> where's copy taste gone?
> 
> If it's a new thing, let's chat :) It might be confusing given the visual
> treatments are so similar to viewer (the icon is identical). We may need to
> page @akemitakagi https://github.com/akemitakagi for a new one.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/guardian/editorial-viewer/pull/56#issuecomment-229603417,
> or mute the thread
> https://github.com/notifications/unsubscribe/AKU_l7zRFBiXJVqTTpr57lky53lBvb7Sks5qQ4ZvgaJpZM4I9Zs-
> .

## 

---

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by mchv** [comment]
👍

**Comment by akemitakagi** [comment]
Hello Nathan and Mario,

Here's the icon for the social share.

Many thanks,

Akemi

On 30 June 2016 at 10:34, Mariot Chauvin notifications@github.com wrote:

> 👍
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/guardian/editorial-viewer/pull/56#issuecomment-229610373,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFsQRUYa5EZVimNEFgyuYQwrbUhAN2Avks5qQ42pgaJpZM4I9Zs-
> .

## 

---

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
