### PR TITLE
Add an additional selector for DCR external link decoration

### PR DESCRIPTION
**Pull request by jfsoul**
## What does this change?

Adds an additional selector for articles rendered by DCR instead of frontend, which I've added in https://github.com/guardian/dotcom-rendering/pull/2192. This is to fix an issue where external links in preview article bodies (rendered by DCR) are opened within the viewer iframe, but do not comply with the CSP.

## How to test

Open an external link in an article supported by DCR (you can tell if the footer contains a `(modern)` label). [Example](https://www.theguardian.com/commentisfree/2020/dec/02/cautious-christmas-covid). It should load in a new tab. Links to other guardian content should continue to load within the viewer iframe.

## How can we measure success?

No error pages for users of composers who attempt to test out external links that are added to their content. They work fine once published, but it's a bit alarming.

## Have we considered potential risks?

Risk of maintaining this loose contract with DCR has been considered. There was in fact a draft PR to solve this directly within DCR, which while possible was overly complex and probably not the right place to solve a viewer-specific requirement.

## Images

N/A

### CODE REVIEW

**Comment by SHession** [comment]
I've tested this locally using the provided example and I don't believe I'm seeing the expected behaviour. When I press an external link I see a banner which reads "This could not be detected as a Guardian page, some features will be unavailable". I also see the same thing when pressing Guardian links within a document. If I press some of the navigation links at the top, I get an iframe within an iframe. Am I doing something wrong?
image

**Comment by jfsoul** [comment]
@SHession apologies, I still need to release the DCR change (linked in the description). I had expected to do that by now, but we've got a flaky test.

**Comment by SHession** [comment]
@jfsoul no problem, let me know when that's done and I will retest.

**Comment by jfsoul** [comment]
Although to be honest, I don't know why you're seeing that behaviour anyway (I highly doubt related to my change). Perhaps links just don't work locally for whatever reason?

**Comment by jfsoul** [comment]
It also behaves this strange way on CODE, without my changes, so I think this is going to be quite hard to test. I think this is fairly safe to release - it's attempting to fix a part of the viewer that is already broken 75% of the time, so worst case is that the other 25% doesn't work and we can quickly revert? Your call.

**Review by SHession — APPROVED** [review]
@jfsoul I've tested this on CODE and I found that the first link worked correctly but then subsequent Guardian links gave me the same banner issue. I agree this should be safe to deploy but I think more investigation into these issues needs to be done. I will create a card in our health backlog to look into this further.

**Comment by jfsoul** [comment]
Great, thanks @SHession I will merge now.

**Pull request merged**
